#! /usr/bin/env python3
# -*- coding: utf-8 -*-
##########################################################################
# NSAp - Copyright (C) CEA, 2022 - 2023
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

"""
Organize the analysis steps.
"""

# System import
import fire
import mmbench.workflow as wf1
import mopoe.workflow as wf2


fire.Fire({
    "train-mopoe": wf2.train_exp,
    "latent": wf1.benchmark_latent_exp,
    "rsa": wf1.benchmark_rsa_exp,
    "pred": wf1.benchmark_pred_exp
})
